repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [ '--line-length=79',
                '--include=\.pyi?$',
                '--exclude=/(.eggs|.git|.hg|.mypy_cache|.tox|.venv|_build|buck-out|build|dist)/' ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: flake8 linting
        entry: flake8
        language: python
        types: [ python ]
