version: '3.8'

services:
  app:
    build: app
    volumes:
      - "./app:/app"
    env_file:
      - .env

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    depends_on:
      - app

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile

    volumes:
      - "./tests:/tests"
      - "./app:/app"
    env_file:
      - .env
    profiles:
      - tests
